### ISSUE TITLE
Burgershot job works but

### ISSUE THREAD

**Issue by xxUnknown13xx** [21FlenN/FN-burgershot#3]
All works fine now, The only thing I get an error from is the phone delivery

This the errors I get.>>>

![bs 1](https://user-images.githubusercontent.com/113321753/197039738-cc270b7f-c780-4a18-98cf-28dcdb779ff0.PNG)

![bs 2](https://user-images.githubusercontent.com/113321753/197039760-4e65577e-eecb-47cd-b280-36b46b499791.PNG)

**Comment by 21FlenN** [comment]
Hi, i know it has been a long time xD, but i kinda went afk, so, you need to change the ps-fuel to LegacyFuel
